### ISSUE TITLE
Not working with QModManager 3.0

### ISSUE THREAD

**Issue by ianschmitz** [ethanfischer/SubnauticaSnapTurningMod#1]
Looks like this mod stopped working with the 3.0 release. Any chance of getting it up and running again?

Many thanks for the mod!

Edit: This may be due to an update to Subnautica itself, and unrelated to QModManager 3.0, as it looks like the Unity APIs changed.

**Comment by ethanfischer** [comment]
Hey @ianschmitz, thanks for submitting this! I'm going to download the steam version and test this out
